import type { App } from 'vue';
import FgAccordion from './components/FgAccordion.vue';
import FgAccordionBody from './components/FgAccordionBody.vue';
import FgAccordionHead from './components/FgAccordionHead.vue';
import FgAccordionItem from './components/FgAccordionItem.vue';
import FgAlert from './components/FgAlert.vue';
import FgCheckbox from './components/FgCheckbox.vue';
import FgCode from './components/FgCode.vue';
import FgError from './components/FgError.vue';
import FgIcon from './components/FgIcon.vue';
import FgIconPicker from './components/FgIconPicker.vue';
import FgInfo from './components/FgInfo.vue';
import FgInput from './components/FgInput.vue';
import FgLabel from './components/FgLabel.vue';
import FgLoader from './components/FgLoader.vue';
import FgRadio from './components/FgRadio.vue';
import FgRichSelect from './components/FgRichSelect.vue';
import FgSelect from './components/FgSelect.vue';
import FgSwitch from './components/FgSwitch.vue';
import FgTabs from './components/FgTabs.vue';
import FgTextarea from './components/FgTextarea.vue';
declare const FadgramVue: {
    install(app: App): void;
};
export default FadgramVue;
export { FgAccordion, FgAccordionBody, FgAccordionHead, FgAccordionItem, FgAlert, FgCheckbox, FgCode, FgError, FgIcon, FgIconPicker, FgInfo, FgInput, FgLabel, FgLoader, FgRadio, FgRichSelect, FgSelect, FgSwitch, FgTabs, FgTextarea, };
